from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional

from .utils import ensure_dir, relpath_posix, safe_filename


def ensure_output_dir(base: Path) -> Path:
    base = base.expanduser()
    return ensure_dir(base)


def make_project_dir(parent: Path, name: str) -> Path:
    parent = ensure_output_dir(parent)
    folder = ensure_dir(parent / safe_filename(name))
    return folder


@dataclass(frozen=True)
class IndexItem:
    title: str
    md_path: Path


def _yaml_escape(value: str) -> str:
    v = value.replace("\r\n", "\n").replace("\r", "\n")
    if "\n" in v:
        # Minimal block scalar for multi-line strings.
        indented = "\n".join("  " + line for line in v.split("\n"))
        return "|\n" + indented
    # Quote everything to avoid YAML edge cases with :, #, etc.
    v = v.replace("\\", "\\\\").replace('"', '\\"')
    return f"\"{v}\""


def build_frontmatter(meta: dict[str, str]) -> str:
    lines = ["---"]
    for k, v in meta.items():
        lines.append(f"{k}: {_yaml_escape(v)}")
    lines.append("---")
    return "\n".join(lines) + "\n\n"


def prepend_frontmatter(markdown: str, meta: dict[str, str]) -> str:
    text = markdown.lstrip("\ufeff")
    if text.startswith("---\n"):
        return markdown
    return build_frontmatter(meta) + markdown.lstrip()


def write_index(output_dir: Path, title: str, items: Iterable[IndexItem]) -> Path:
    lines: list[str] = [f"# {title}".strip(), ""]
    count = 0
    for it in items:
        rel = relpath_posix(it.md_path, output_dir)
        lines.append(f"- [{it.title}]({rel})")
        count += 1
    lines.append("")
    lines.append(f"_Generated by DocHarvester. Items: {count}_")
    out = output_dir / "index.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def pick_title_from_html(html_title: Optional[str], fallback: str) -> str:
    if html_title:
        t = html_title.strip()
        if t:
            return t
    return fallback

